version : '2'
services:
         mongo:
               image: mongo
               ports:
                  - "27017:27017"
               expose:
                 - "27017"
               volumes:
                  - "/home/deoliveira/work/docker/data:/data/db"
         task-api:
               build:
                     context: .
                     args:
                          - TASK_API_PORT=8090
                          - TASK_API_MONGO_HOST=mongo
               image: deoliveira/task-api
               depends_on:
                  - mongo
               ports:
                  - "8090:8080"
